// apps/shell/src/lib/RightPane.svelte

<script lang="ts">
    import AiChat from '$lib/AiChat.svelte';
    import ProjectHistory from '$lib/ProjectHistory.svelte';
    import MixIQ from '$lib/MixIQ.svelte';
    import DocViewer from './DocViewer.svelte';
    import ProjectHealth from './ProjectHealth.svelte';
    
    export let projectPath: string;
    export let activeTab: 'chat' | 'history' | 'analysis' | 'docs' | 'health' = 'chat';
    export let code: string;
    export let language: string;

    function getTabClass(tabName: typeof activeTab) {
        return activeTab === tabName 
            ? 'border-blue-500 text-white' 
            : 'border-transparent text-gray-400 hover:text-white hover:border-gray-500';
    }
</script>

<div class="flex flex-col h-full text-gray-300">
    <div class="flex-shrink-0 border-b border-gray-600 flex text-sm">
        <button 
            on:click={() => activeTab = 'chat'} 
            class="flex-1 p-3 text-center font-bold border-b-2 transition-colors duration-150 {getTabClass('chat')}"
        >
            AI Assistant
        </button>
        <button 
            on:click={() => activeTab = 'history'} 
            class="flex-1 p-3 text-center font-bold border-b-2 transition-colors duration-150 {getTabClass('history')}"
        >
            History
        </button>
         <button 
            on:click={() => activeTab = 'analysis'} 
            class="flex-1 p-3 text-center font-bold border-b-2 transition-colors duration-150 {getTabClass('analysis')}"
        >
            Analysis
        </button>
         <button 
            on:click={() => activeTab = 'docs'} 
            class="flex-1 p-3 text-center font-bold border-b-2 transition-colors duration-150 {getTabClass('docs')}"
        >
            Docs
        </button>
        <button 
            on:click={() => activeTab = 'health'} 
            class="flex-1 p-3 text-center font-bold border-b-2 transition-colors duration-150 {getTabClass('health')}"
        >
            Saúde
        </button>
    </div>
    <div class="flex-1 overflow-y-auto">
        {#if activeTab === 'chat'}
            <AiChat {projectPath} />
        {:else if activeTab === 'history'}
            <ProjectHistory {projectPath} />
        {:else if activeTab === 'analysis'}
            <MixIQ {code} {language} />
        {:else if activeTab === 'docs'}
            <DocViewer {code} {language} {projectPath} active={activeTab === 'docs'} />
        {:else if activeTab === 'health'}
            <ProjectHealth {projectPath} active={activeTab === 'health'} />
        {/if}
    </div>
</div>

// components/RightPane.tsx

import React from 'react';
import AiChat from './AiChat';
import TechDebtRadar from './TechDebtRadar';
import { ChatMessage, TechDebtReport } from '../types';

type RightPaneView = 'chat' | 'radar';

interface RightPaneProps {
    activeTab: RightPaneView;
    onTabChange: (tab: RightPaneView) => void;
    // AI Chat props
    chatMessages: ChatMessage[];
    isChatLoading: boolean;
    onSendMessage: (text: string) => void;
    initialPrompt: string | null;
    onPromptHandled: () => void;
    // Tech Debt Radar props
    techDebtReport: TechDebtReport | null;
    isRadarLoading: boolean;
}

const RightPane: React.FC<RightPaneProps> = (props) => {
    const { activeTab, onTabChange } = props;

    const getTabClass = (tabName: RightPaneView) => {
        return activeTab === tabName 
            ? 'border-[var(--color-accent)] text-[var(--color-text-primary)] bg-[var(--color-bg-secondary)]' 
            : 'border-transparent text-[var(--color-text-tertiary)] hover:text-[var(--color-text-primary)] hover:border-[var(--color-text-quaternary)]';
    };

    return (
        <div className="w-[450px] bg-[var(--color-bg-secondary)] flex flex-col border-l border-[var(--color-border-primary)]">
            <div className="flex-shrink-0 border-b border-[var(--color-border-primary)] flex">
                <button 
                    onClick={() => onTabChange('chat')} 
                    className={`flex-1 p-3 text-center font-semibold border-b-2 transition-colors duration-150 text-sm ${getTabClass('chat')}`}
                >
                    AI Assistant
                </button>
                <button 
                    onClick={() => onTabChange('radar')} 
                    className={`flex-1 p-3 text-center font-semibold border-b-2 transition-colors duration-150 text-sm ${getTabClass('radar')}`}
                >
                    Tech-Debt Radar
                </button>
            </div>
            <div className="flex-1 min-h-0 bg-[var(--color-bg-secondary)]">
                {activeTab === 'chat' && (
                    <AiChat 
                        messages={props.chatMessages}
                        isLoading={props.isChatLoading}
                        onSendMessage={props.onSendMessage}
                        initialPrompt={props.initialPrompt}
                        onPromptHandled={props.onPromptHandled}
                    />
                )}
                {activeTab === 'radar' && (
                    <TechDebtRadar
                        report={props.techDebtReport}
                        isLoading={props.isRadarLoading}
                    />
                )}
            </div>
        </div>
    );
};

export default RightPane;
